### ISSUE TITLE
Native image support

### ISSUE THREAD

**Issue by DanielLiu1123** [DanielLiu1123/grpc-starter#32]
If this feature gets strong feedback from the community, I will consider implementing it.

- [x] #58
- [x] #59
- [x] #64  
- [x] #66
- [x] #69

**Comment by outlndrr** [comment]
It would be really cool!

**Comment by kevin2-cyber** [comment]
Please implement it would be cool

**Comment by DanielLiu1123** [comment]
native-image is supported starting from version [3.3.5.1](https://github.com/DanielLiu1123/grpc-starter/releases/tag/v3.3.5.1)!

Please refer to [native-image example](https://github.com/DanielLiu1123/grpc-starter/tree/main/examples/native-image).

**Comment by DanielLiu1123** [comment]
native-image is supported for all modules starting from version [3.3.5.2](https://github.com/DanielLiu1123/grpc-starter/releases/tag/v3.3.5.2)!
