### ISSUE TITLE
RFE server:  make isAutoStartup/getPhase configurable

### ISSUE THREAD

**Issue by space88man** [DanielLiu1123/grpc-starter#68]
RFE: make the auto-startup of server configurable - this will allow user to control when to start the server
[Updated] may also be useful to have `getPhase()` configurable
```
# new properties - add to GrpcServerProperties
grpc.server.phase = 99999999
# true | false: default true
grpc.server.auto-startup = true
```

which will control

```
public class DefaultGrpcServer  implements SmartLifecycle, ...{
   // should be set by auto-configuration from GrpcServerProperties
   // default: Integer.MAX_VALUE - 1
    private int phase =  Integer.MAX_VALUE - 1; 

    // setter
    void setPhase(int val) {
        this.phase = val;
    }

    // getter
    @Override
    boolean getPhase() {
         return this.phase;
     }

   // should be set by auto-configuration from GrpcServerProperties
   // default: true
    private boolean autoStartup = true;

    // setter
    void setAutoStartup(boolean val) {
        this.autoStartup = val;
    }

    // getter
    @Override
    boolean isAutoStartup() {
         return autoStartup;
     }
}
```

**Comment by DanielLiu1123** [comment]
Is `grpc.server.enabled=false` what you’re looking for? When set to `false`, the gRPC server will not auto startup.
```yaml
grpc:
  server:
    enabled: false
```

**Comment by space88man** [comment]
> Is `grpc.server.enabled=false` what you’re looking for? When set to `false`, the gRPC server will not auto startup.
> 
> ```yaml
> grpc:
>   server:
>     enabled: false
> ```

That setting seems to disable the `@Bean` completely, right?

I want the `GrpcServer` bean but delay the startup (I have other beans that need to do stuff before the gRPC server can run).

**Comment by DanielLiu1123** [comment]
> That setting seems to disable the `@Bean` completely, right?

yes

> I want the GrpcServer bean but delay the startup (I have other beans that need to do stuff before the gRPC server can run).

It seems that the `auto-startup` configuration might be useful in some cases; I’ll consider adding it. In the meantime, could you tell me more about your use case? I’d like to see if I can help you solve this issue.

Here’s a more hacky workaround:
```java
@Bean
static BeanPostProcessor hackGrpcServerBeanPostProcessor() {
    return new BeanPostProcessor() {
        @Override
        public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
            if (bean instanceof GrpcServer server) {
                return Proxy.newProxyInstance(server.getClass().getClassLoader(), new Class<?>[]{GrpcServer.class}, (proxy, method, args) -> {
                    if (method.getName().equals("isAutoStartup")) {
                        return false;
                    }
                    return method.invoke(server, args);
                });
            }
            return bean;
        }
    };
}
```

**Comment by space88man** [comment]
My use case is some components asynchronously populate some caches when the ApplicationContext is ready. The gRPC service should serve data from these caches.

Currently I extend `DefaultGrpcServer` and set `isAutoStartup()` to return `false`. Then when the caches are ready I call the `start()` method.

Perhaps `DefaultGrpcServer` could also allow setting `getPhase()`; then the caching services could be in an earlier phase.

```
# new property
grpc.server.phase = NNN 
```

Then 

```
@Value("${grpc.server.phase:99999999}")
private int phase;

@Override
int getPhase() { return phase; }
```

**Comment by DanielLiu1123** [comment]
Perhaps you could try `SmartInitializingSingleton`, which executes after all beans are initialized but before `Lifecycle` beans start. It’s ideal for initializing caches and data. This way, you wouldn’t need to manually start the `GrpcServer`.

Example:
```java
@Bean
public SmartInitializingSingleton populateCache() {
    return () -> {
        // populate cache here
    };
}
```

From [Spring docs](https://docs.spring.io/spring-framework/reference/core/beans/factory-nature.html#beans-factory-lifecycle-initializingbean):
```text
For a scenario where expensive post-initialization activity is to be triggered, 
e.g. asynchronous database preparation steps, your bean should either implement SmartInitializingSingleton.afterSingletonsInstantiated() 
or rely on the context refresh event: implementing ApplicationListener<ContextRefreshedEvent> 
or declaring its annotation equivalent @EventListener(ContextRefreshedEvent.class). 
Those variants come after all regular singleton initialization and therefore outside of any singleton creation lock.
```
